import { QuizService } from '../../controllers/quizController';
import { prisma } from '../../infra/prisma/client';
import jwt from 'jsonwebtoken';

const JWT_SECRET = 'test-secret';
process.env.JWT_SECRET = JWT_SECRET;

class Actor {
    id: string;
    email: string;
    name: string;
    token: string;
    sessionId: string;

    constructor(user: { id: string; email: string; name: string }) {
        this.id = user.id;
        this.email = user.email;
        this.name = user.name;
        this.sessionId = `60f7e1b2f1a2b3c4d5e6f7a${user.id.substring(0, 1)}`; // Must be 24 hex chars for ObjectId in some contexts, but here it's just a string in SQLite test
        this.token = jwt.sign({ user: { id: user.id }, sessionId: this.sessionId }, JWT_SECRET);
    }

    static user(user: { id: string; email: string; name: string }) {
        return new Actor(user);
    }
}

describe('Polling Sync Consistency & Long Polling (Service Layer)', () => {
    const userA = { id: 'cmnq1t11v0000j6tdz262ua6x', email: 'a@test.com', name: 'Alice' };
    let actorA: Actor;
    let quizService: QuizService;

    beforeEach(async () => {
        await prisma.quizParticipant.deleteMany();
        await prisma.quizSession.deleteMany();
        await prisma.session.deleteMany();
        await prisma.user.deleteMany();

        await prisma.user.create({ data: { id: userA.id, email: userA.email, name: userA.name } });
        actorA = Actor.user(userA);
        // In the real system, session id is autogenerated, but here we provide it.
        // Prisma Client for MongoDB might complain if ID is not ObjectId format if we use real DB,
        // but for SQLite test it should be fine as long as it's a string.
        await prisma.session.create({
            data: {
                userId: userA.id,
                sessionToken: actorA.token,
                expires: new Date(Date.now() + 3600000)
            }
        });
        quizService = new QuizService(prisma);
    });

    afterAll(async () => {
        await prisma.$disconnect();
    });

    /**
     * @Doc("Scenario J: Service Layer Long Polling logic")
     */
    test('should_detect_version_match_and_be_prepared_to_wait', async () => {
        const qSession = await quizService.getOrCreateDailyQuizSession(actorA);
        if (!qSession) throw new Error('Session creation failed');

        await quizService.findOrCreateParticipant(qSession, actorA);

        const sessionFromDb = await quizService.getUserActiveSession(actorA.id);
        expect(sessionFromDb).toBeDefined();

        const currentVersion = sessionFromDb!.updatedAt ? sessionFromDb!.updatedAt.getTime() : 0;
        const versionFromDb = sessionFromDb!.updatedAt ? sessionFromDb!.updatedAt.getTime() : 0;

        expect(versionFromDb).toBe(currentVersion);
    });

    /**
     * @Doc("Scenario I: Polling Synchronization Consistency via Service")
     */
    test('should_return_updated_participants_given_version_mismatch', async () => {
        const qSession = await quizService.getOrCreateDailyQuizSession(actorA);
        if (!qSession) throw new Error('Session creation failed');

        await quizService.findOrCreateParticipant(qSession, actorA);

        // Actor-driven verification of state
        const session = await quizService.getUserActiveSession(actorA.id);
        expect(session).toBeDefined();

        const participants = await quizService.getSessionParticipants(session!.id);
        expect(participants.length).toBe(1);
        expect(participants[0].userId).toBe(actorA.id);
    });

    test('should_enforce_session_limit_and_return_null_given_max_sessions', async () => {
        await prisma.quizSession.deleteMany();
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        // Fill up to 10 sessions with 5 participants each to ensure they are NOT available
        for(let i=0; i<10; i++) {
            const qSess = await prisma.quizSession.create({ data: { date: today, startTime: new Date() } });
            for(let j=0; j<5; j++) {
                const u = await prisma.user.create({ data: { email: `user-${i}-${j}@test.com`, name: `User ${i}-${j}` } });
                await prisma.quizParticipant.create({ data: { userId: u.id, sessionId: qSess.id } });
            }
        }

        const session = await quizService.getOrCreateDailyQuizSession(actorA);
        expect(session).toBeNull();
    });
});
