export class LearningSession {
  id: string;
  userId: string;
  allQuestionIds: string[];
  questionIds: string[]; // Current subset
  subsetHistory: string[][];
  currentQuestionIndex: number;
  answers: { [questionId: string]: { answer: string; isCorrect: boolean } };
  summary: {
    strengths: string[];
    weaknesses: string[];
  };
  startTime: number;
  endTime: number | null;
  feedbackBatchesGenerated: number;

  constructor(id:string, userId: string, allQuestionIds: string[]) {
    this.id = id;
    this.userId = userId;
    this.allQuestionIds = allQuestionIds;
    this.questionIds = [];
    this.subsetHistory = [];
    this.currentQuestionIndex = 0;
    this.answers = {};
    this.summary = { strengths: [], weaknesses: [] };
    this.startTime = Date.now();
    this.endTime = null;
    this.feedbackBatchesGenerated = 0;
  }

  answerQuestion(questionId: string, answer: string, isCorrect: boolean) {
    this.answers[questionId] = { answer, isCorrect };
    this.currentQuestionIndex++;
  }

  end() {
    this.endTime = Date.now();
    // Summary will be generated by a service and set in the slice.
  }
}
